server:
  port: 8883
  contextPath: /inventory-service
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/myth_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 20
        minIdle: 20
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    application:
      name: inventory-service
   #activemq:
    #   broker-url: tcp://120.76.52.162:61616
    #   user: happylife
    #   password: happylifeplat01
    #   trust-all: true
   #rabbitmq:
    #    host: localhost
    #    port: 5672
    #    username: guest
    #    password: guest
    #rocketmq:
        #namesrvAddr: localhost:9876
        #consumerGroupName: inventory
        #instanceName: inventory
    kafka:
        consumer:
           bootstrap-servers: 192.168.1.91:9092
           group-id: test
           auto-offset-reset: earliest
           enable-auto-commit: true
           auto-commit-interval: 100
           key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
           value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
mybatis:
  type-aliases-package: org.dromara.myth.demo.springcloud.inventory.api.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/

org:
  dromara :
      myth :
        serializer : kryo
        repositorySupport : db
        mythDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://192.168.1.98:3306/myth?useUnicode=true&amp;characterEncoding=utf8
                 username : root
                 password : 123456


inventory-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.myth.bonuspoint: info
        org.dromara.myth.lottery: debug
        org.dromara.myth: debug

    path: "./logs"

