server:
  port: 8882
  contextPath: /account-service
  address: 0.0.0.0


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/myth_account?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: 123456
    application:
      name: account-service
   #activemq:
        #   broker-url: tcp://120.76.52.162:61616
        #   user: happylife
        #   password: happylifeplat01
        #   trust-all: true
   #rabbitmq:
        #    host: localhost
        #    port: 5672
        #    username: guest
        #    password: guest
    #rocketmq:
          #namesrvAddr: localhost:9876
          #consumerGroupName: account
          #instanceName: account
    kafka:
            consumer:
               bootstrap-servers: 192.168.1.91:9092
               group-id: test
               auto-offset-reset: earliest
               enable-auto-commit: true
               auto-commit-interval: 100
               key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
               value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

mybatis:
  type-aliases-package: org.dromara.myth.demo.springcloud.account.api.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/

org:
  dromara :
      myth :
        serializer : kryo
        repositorySupport : db
        mythDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://192.168.1.98:3306/myth?useUnicode=true&amp;characterEncoding=utf8
                 username : root
                 password : 123456

       # repositorySupport : redis
       #         hostName  : 192.168.1.68
       #         port      :  6379
       #         password  :


       # repositorySupport : zookeeper
       #         host      : 192.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /myth

       # repositorySupport : mongodb
       #       mongoDbUrl  : 192.168.1.68:27017
       #       mongoDbName  :  youname
       #       mongoUserName  : xiaoyu
       #       mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /youpath
       #         prefix    :  youpath




account-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.myth.bonuspoint: info
        org.dromara.myth.lottery: debug
        org.dromara.myth: debug

    path: "./logs"

