server:
  port: 8083
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/myth_order?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456


mybatis:
  type-aliases-package: com.github.myth.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.github.myth.bonuspoint: info
        com.github.myth.lottery: debug
        com.github.myth: debug
        io.netty: info

    path: "./logs"

